CREATE TYPE FEED_ENTRY_STATE AS ENUM ('NEW', 'COMPLETED', 'FAILED');

ALTER TABLE FEED_ENTRY ADD COLUMN STATE FEED_ENTRY_STATE NOT NULL DEFAULT 'NEW';
ALTER TABLE FEED_ENTRY ADD COLUMN FAIL_COUNT INTEGER NOT NULL DEFAULT 0;
ALTER TABLE FEED_ENTRY ADD COLUMN LAST_FAIL TIMESTAMPTZ;
ALTER TABLE FEED_ENTRY ADD COLUMN CREATED TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE FEED ADD COLUMN CREATED TIMESTAMPTZ NOT NULL DEFAULT now();
