CREATE TYPE FEED_STATE AS ENUM ('ACTIVE', 'FAILED');

CREATE TABLE FEED (
    ID UUID,
    URL TEXT CONSTRAINT unique_url UNIQUE,
    TITLE TEXT,

    STATE FEED_STATE NOT NULL,
    FAIL_COUNT INTEGER NOT NULL DEFAULT 0,
    LAST_ATTEMPT TIMESTAMPTZ,
    LAST_SUCCESS TIMESTAMPTZ,
    LAST_FAIL TIMESTAMPTZ,

    PRIMARY KEY (ID)
);

CREATE TABLE FEED_ENTRY (
  ID UUID,

  FEED_ID UUID REFERENCES FEED (ID) ON DELETE CASCADE,
  URL TEXT CONSTRAINT unique_entry_url UNIQUE,

  TITLE TEXT,

  ENTRY_CONTENT_HTML TEXT,
  ENTRY_CONTENT_TEXT TEXT,

  LINK_CONTENT_HTML TEXT,
  LINK_CONTENT_TEXT TEXT

);